#### PyPi Package : NumPy

In [1]:
# pip install numpy
import numpy as np

# Array Initialization

In [2]:

# Array Initialization
# In this exercise, you will learn how to initialize an array in Python.
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [3]:
# initialize an array as float type
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# initialize an array as 3 dimension
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(c)



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Get Dimension

In [5]:
# Get Dimension
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


## Get Shape

In [6]:
# Get Shape
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(2, 2, 2)


## Get Type

In [7]:
# Get Type
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int32


## Get Size (bytes per element)

In [8]:
# Get Size (bytes per element)
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

4
8
4


## Get total size (bytes for the whole array)

In [9]:
# Get total size (bytes for the whole array)
print(a.nbytes)
print(b.nbytes)
print(c.nbytes)

12
48
32


## Get number of elements

In [10]:
# Get number of elements
print(a.size)
print(b.size)
print(c.size)

3
6
8


# Accessing/Changing specific elements, rows, columns, etc

In [13]:
a = np.array([[1, 2, 3, 4, 5, 6, 7,8,9], [10, 20, 30, 40, 50, 60, 70,80,90]])
b = np.array([[1, 2, 3, 4, 5, 6, 7,8,9], [10, 20, 30, 40, 50, 60, 70,80,90],[11,21,31,41,51,61,71,81,91]])


## Get a specific element

In [14]:
# Get a specific element
print(a)
print(a[0, 2])
print(a[0, 5])
print(a[1, 5])

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]
3
6
60


## Get a specific row

In [15]:
# Get a specific row
print(a[0, :])
print(a[0, :3])
print(a[0, 0:-1])
print(a[0, 2:4])

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[1 2 3 4 5 6 7 8]
[3 4]


## Get a specific column

In [16]:
# Get a specific column
print(a)
print("second column using index",a[:, 1])
print(a[1:, 3])
print("**************")
print(b)
print(b[:,0])

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]
second column using index [ 2 20]
[40]
**************
[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]
 [11 21 31 41 51 61 71 81 91]]
[ 1 10 11]


## Get a specific range of elements

In [72]:
# Get a specific range of elements
print(a)
print("*********")
print(a[0, 1:-1:2])
print("************")
print(b)
print("************")
print(b[2, 1:-1:2])
print(b[0:3, 1:-1:2])

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]
*********
[2 4 6 8]
************
[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]
 [11 21 31 41 51 61 71 81 91]]
************
[21 41 61 81]
[[ 2  4  6  8]
 [20 40 60 80]
 [21 41 61 81]]


## Modify an element and replace a column

In [17]:
# Modify an element and replace a column
print(a)
print("*************")
a[1, 5] = 22
print(a)
print("****************")
a[:, 2] = [0, 0]
print(a)

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]
*************
[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 22 70 80 90]]
****************
[[ 1  2  0  4  5  6  7  8  9]
 [10 20  0 40 50 22 70 80 90]]


# Initializing Different Types of Arrays

In [18]:
# All 0s matrix
print(np.zeros((2, 3)))
print(np.zeros((2, 3)).ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
2


In [19]:
# All 1s matrix
print((np.ones((4, 2, 2), dtype='int32')))
print((np.ones((4, 2, 2), dtype='int32')).ndim)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
3


In [87]:
print((np.ones((4, 3, 3), dtype='int32')))
print((np.ones((4, 3, 3), dtype='int32')).ndim)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
3


In [20]:
# Any other number
print(np.full((2, 2), 99))

[[99 99]
 [99 99]]


In [21]:
# Any other number (full_like)
print(np.full_like(a, 4))

[[4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4]]


In [22]:
# Random decimal numbers
print(np.random.rand(3, 3))

[[0.15846978 0.7651814  0.86670403]
 [0.39771192 0.56945293 0.2441387 ]
 [0.45738856 0.48440844 0.93893072]]


In [23]:
# Random Integer values
print(np.random.randint(10, 20, size=(3, 3)))

[[16 10 14]
 [18 14 18]
 [17 13 13]]


In [24]:
# The identity matrix
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


# Mathematics

In [91]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


## Basic Operations

In [92]:
print(a)
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


## Element-wise Operations

In [93]:
b = np.array([1, 0, 1, 0])
print(a)
print(b)
print("*********")
print(a + b)
print("********")
print(a ** 2)
print(np.cos(a))

[1 2 3 4]
[1 0 1 0]
*********
[2 2 4 4]
********
[ 1  4  9 16]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


# Linear Algebra

In [95]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)
print(a)
print("")
print("")
print(b)
print("")
print("")
print(np.matmul(a, b))

[[1. 1. 1.]
 [1. 1. 1.]]


[[2 2]
 [2 2]
 [2 2]]


[[6. 6.]
 [6. 6.]]


# Statistics

In [96]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(np.min(stats))
print(np.max(stats, axis=1))
print(np.sum(stats, axis=0))

1
[3 6]
[5 7 9]
